### ISSUE TITLE
what command does it provide?

### ISSUE THREAD

**Issue by Zuckonit** [ajenhl/tacl-extra#1]
any guide to how to use this?

**Comment by ajenhl** [comment]
As per the README and documentation at http://tacl-extra.readthedocs.io/en/latest/ there are four commands that are part of the package: `int-all`, `jitc`, `lifetime`, and `paternity`. How each of these commands work can be found by running it with the -h flag. Eg, `jitc -h`

**Comment by Zuckonit** [comment]
![image](https://user-images.githubusercontent.com/988858/69255977-ae73bb00-0bf3-11ea-87ed-d3cd765e233a.png)

@ajenhl

**Comment by ajenhl** [comment]
These commands are not tacl sub-commands (like `tacl ngrams` or `tacl diff`) but rather stand-alone commands, so just `jitc` or `int-all`.

**Comment by Zuckonit** [comment]
get it, thanks very much
